// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("BrightSword.SwissKnife")]
[assembly: AssemblyProductAttribute("BrightSword.SwissKnife")]
[assembly: AssemblyDescriptionAttribute("A collection of general programming utilities")]
[assembly: AssemblyVersionAttribute("1.0.44")]
[assembly: AssemblyFileVersionAttribute("1.0.44")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.44";
    }
}
