//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace BrightSword.SwissKnife.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("23")]
        public uint Realm_UniqueID {
            get {
                return ((uint)(this["Realm_UniqueID"]));
            }
            set {
                this["Realm_UniqueID"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("97")]
        public ushort Server_UniqueID {
            get {
                return ((ushort)(this["Server_UniqueID"]));
            }
            set {
                this["Server_UniqueID"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("11")]
        public ushort Application_UniqueID {
            get {
                return ((ushort)(this["Application_UniqueID"]));
            }
            set {
                this["Application_UniqueID"] = value;
            }
        }
    }
}
